name: tuki_ofertas
description: "Tuki Ofertas - Encuentra las mejores ofertas en Colombia"
publish_to: 'none'
version: 1.0.6+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/icon/icon_ios.png

flutter_launcher_icons:
  android: false                          # НЕ трогаем Android иконки
  ios: true
  image_path: "assets/icon/icon_ios.png"  # непрозрачная иконка для iOS
  remove_alpha_ios: true                  # на всякий случай убираем альфу
